on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.2.2

      - name: Install system dependencies
        run: sudo apt install libasound2-dev libudev-dev pkg-config

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1.10.1
        with:
          components: clippy,rustfmt

      - name: Check Formatting
        run: >
          cargo fmt
          --all
          --check

      - name: Lint with Clippy
        run: >
          cargo clippy
          --all-targets
          --all-features
          --no-deps
          --
          --deny warnings
